[package]
name = "cmdi"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["env"] }
clap_complete = "4.5"
rustyline = "14.0.0"
shell-words = "1.0"
anyhow = "1.0"
